# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script:
    git remote set-url upstream https://github.com/rastislavsvoboda/zvjs-external.git
    
    git checkout master
    
    git pull

    git push upstream
    
    # echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
