version: '3.4'

services:
  blazorapp1:
    image: ${DOCKER_REGISTRY-}blazorapp1
    build:
      context: .
      dockerfile: BlazorApp1/Dockerfile

  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

